version: "3.5"

services:

  db:
    image: postgres:14-alpine
    restart: always
    hostname: db
    container_name: db
    environment:
      POSTGRES_USER: $AND_DB_USER
      POSTGRES_PASSWORD: $AND_DB_PASS
      POSTGRES_DB: $AND_DB_NAME
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - "5432:5432"
